import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

// Translation keys - Complete translations for all pages
const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.products': 'المنتجات',
    'nav.services': 'الخدمات',
    'nav.projects': 'المشاريع',
    'nav.blog': 'المدونة',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'nav.calculator': 'حاسبة الطاقة',
    'nav.cart': 'السلة',
    'nav.myOrders': 'طلباتي',
    'nav.dashboard': 'لوحة التحكم',
    'nav.getQuote': 'احصل على عرض',

    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.success': 'تم بنجاح',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.all': 'الكل',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.close': 'إغلاق',
    'common.submit': 'إرسال',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.view': 'عرض',
    'common.download': 'تحميل',
    'common.print': 'طباعة',
    'common.share': 'مشاركة',
    'common.email': 'البريد الإلكتروني',
    'common.phone': 'الهاتف',
    'common.address': 'العنوان',
    'common.name': 'الاسم',
    'common.price': 'السعر',
    'common.quantity': 'الكمية',
    'common.total': 'الإجمالي',
    'common.status': 'الحالة',
    'common.date': 'التاريخ',
    'common.language': 'اللغة',
    'common.arabic': 'العربية',
    'common.english': 'English',
    'common.moreInfo': 'معلومات أكثر',
    'common.readMore': 'اقرأ المزيد',
    'common.viewAll': 'عرض الكل',
    'common.contactUs': 'تواصل معنا',
    'common.learnMore': 'اكتشف المزيد',
    'common.getStarted': 'ابدأ الآن',
    'common.freeConsultation': 'استشارة مجانية',
    'common.currency': 'ج.س',

    // Homepage
    'home.hero.title': 'حلول طاقة متكاملة للسودان',
    'home.hero.subtitle': 'نقدم أفضل أنظمة الطاقة الشمسية والمراقبة والإنذار بأعلى جودة وأفضل الأسعار',
    'home.hero.cta': 'تصفح المنتجات',
    'home.hero.calculator': 'احسب احتياجاتك',
    'home.hero.freeConsultation': 'احصل على استشارة مجانية',
    'home.hero.discoverServices': 'اكتشف خدماتنا',
    'home.hero.trustedPartner': 'شريكك الموثوق في الحلول الهندسية',
    'home.hero.integratedSolutions': 'حلول هندسية',
    'home.hero.innovative': 'متكاملة ومبتكرة',
    'home.hero.description': 'نقدم أفضل الحلول في مجالات الطاقة الشمسية، أنظمة المراقبة، والماكينات الصناعية بأعلى معايير الجودة العالمية',
    'home.hero.mainTitle': 'نبني مستقبلاً مستداماً بالطاقة النظيفة',
    'home.hero.mainSubtitle': 'الرائدون في حلول الطاقة الشمسية والأمن والماكينات الصناعية في السودان',
    'home.hero.since': 'منذ 2009',
    'home.hero.companyName': 'أعمال مازن الزبير للطاقة الشمسية',
    'home.featured': 'منتجات مميزة',
    'home.featured.title': 'اكتشف أفضل منتجاتنا',
    'home.featured.subtitle': 'مجموعة مختارة من أفضل المنتجات في الطاقة الشمسية وأنظمة المراقبة والماكينات الصناعية',
    'home.featured.viewAll': 'عرض جميع المنتجات',
    'home.services': 'خدماتنا',
    'home.services.title': 'خدماتنا المتميزة',
    'home.services.subtitle': 'نقدم مجموعة شاملة من الخدمات الهندسية المتخصصة',
    'home.projects': 'مشاريعنا',
    'home.projects.title': 'أحدث مشاريعنا',
    'home.projects.subtitle': 'نفتخر بمشاريعنا الناجحة في جميع أنحاء السودان',
    'home.blog': 'آخر المقالات',
    'home.blog.title': 'مدونتنا',
    'home.blog.subtitle': 'آخر الأخبار والمقالات المفيدة في مجال الطاقة والتقنية',
    'home.blog.readArticle': 'اقرأ المقال',
    'home.contact': 'تواصل معنا',
    'home.newsletter': 'النشرة البريدية',
    'home.newsletter.desc': 'اشترك في نشرتنا البريدية لتصلك أحدث العروض والأخبار',
    'home.stats.projects': 'مشروع منجز',
    'home.stats.experience': 'سنة خبرة',
    'home.stats.clients': 'عميل راضٍ',
    'home.stats.support': 'دعم فني',
    'home.whyUs': 'لماذا نحن؟',
    'home.whyUs.title': 'لماذا تختار أعمال مازن الزبير للطاقة الشمسية؟',
    'home.whyUs.subtitle': 'نتميز بالجودة والاحترافية في جميع خدماتنا',
    'home.cta.title': 'هل أنت جاهز لبدء مشروعك؟',
    'home.cta.subtitle': 'تواصل معنا اليوم للحصول على استشارة مجانية وعرض أسعار مخصص لاحتياجاتك',
    'home.cta.button': 'تواصل معنا الآن',
    'home.cta.whatsapp': 'تواصل عبر واتساب',

    // Services
    'services.solar.title': 'حلول الطاقة الشمسية',
    'services.solar.desc': 'أنظمة طاقة شمسية متكاملة للمنازل والمنشآت التجارية والصناعية مع ضمان الجودة والكفاءة العالية',
    'services.surveillance.title': 'أنظمة المراقبة والأمن',
    'services.surveillance.desc': 'كاميرات مراقبة عالية الدقة من هيك فيشن مع حلول أمنية متطورة لحماية ممتلكاتك',
    'services.industrial.title': 'الماكينات الصناعية',
    'services.industrial.desc': 'ماكينات التعبئة والتغليف وخطوط الإنتاج المتكاملة مع الدعم الفني والصيانة',
    'services.maintenance.title': 'الصيانة والدعم',
    'services.maintenance.desc': 'خدمات صيانة دورية ودعم فني متواصل لجميع الأنظمة',

    // Products
    'products.title': 'منتجاتنا',
    'products.subtitle': 'اكتشف مجموعتنا الواسعة من المنتجات عالية الجودة',
    'products.search': 'ابحث عن منتج...',
    'products.category': 'الفئة',
    'products.price': 'السعر',
    'products.sort': 'ترتيب حسب',
    'products.sortNewest': 'الأحدث',
    'products.sortPriceAsc': 'السعر: من الأقل للأعلى',
    'products.sortPriceDesc': 'السعر: من الأعلى للأقل',
    'products.sortNameAsc': 'الاسم: أ-ي',
    'products.new': 'جديد',
    'products.discount': 'خصم',
    'products.outOfStock': 'نفذت الكمية',
    'products.inStock': 'متوفر',
    'products.lowStock': 'كمية محدودة',
    'products.addToCart': 'أضف للسلة',
    'products.addedToCart': 'تم الإضافة للسلة',
    'products.quickView': 'عرض سريع',
    'products.details': 'تفاصيل المنتج',
    'products.specifications': 'المواصفات',
    'products.reviews': 'التقييمات',
    'products.related': 'منتجات مشابهة',
    'products.features': 'المميزات',
    'products.description': 'الوصف',
    'products.noProducts': 'لا توجد منتجات',
    'products.itemsLeft': 'متبقي {count} قطعة فقط!',
    'products.showFilters': 'عرض الفلاتر',
    'products.hideFilters': 'إخفاء الفلاتر',
    'products.priceRange': 'نطاق السعر',
    'products.availability': 'التوفر',
    'products.onSale': 'عروض',

    // Cart
    'cart.title': 'سلة التسوق',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.emptyDesc': 'لم تقم بإضافة أي منتجات بعد. ابدأ التسوق الآن!',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.shipping': 'الشحن',
    'cart.shippingFree': 'مجاني',
    'cart.shippingCalc': 'يُحسب عند الدفع',
    'cart.discount': 'الخصم',
    'cart.total': 'الإجمالي',
    'cart.checkout': 'إتمام الطلب',
    'cart.continueShopping': 'متابعة التسوق',
    'cart.coupon': 'كود الخصم',
    'cart.applyCoupon': 'تطبيق',
    'cart.remove': 'إزالة',
    'cart.updateQuantity': 'تحديث الكمية',
    'cart.orderSummary': 'ملخص الطلب',

    // Checkout
    'checkout.title': 'إتمام الطلب',
    'checkout.customerInfo': 'معلومات العميل',
    'checkout.shippingAddress': 'عنوان الشحن',
    'checkout.paymentMethod': 'طريقة الدفع',
    'checkout.cashOnDelivery': 'الدفع عند الاستلام',
    'checkout.bankTransfer': 'تحويل بنكي',
    'checkout.placeOrder': 'تأكيد الطلب',
    'checkout.processing': 'جاري معالجة الطلب...',
    'checkout.fullName': 'الاسم الكامل',
    'checkout.email': 'البريد الإلكتروني',
    'checkout.phone': 'رقم الهاتف',
    'checkout.city': 'المدينة',
    'checkout.address': 'العنوان التفصيلي',
    'checkout.notes': 'ملاحظات إضافية',

    // Orders
    'orders.title': 'طلباتي',
    'orders.empty': 'لا توجد طلبات حتى الآن',
    'orders.emptyDesc': 'ابدأ بالتسوق الآن لإنشاء أول طلب لك.',
    'orders.browseProducts': 'تصفح المنتجات',
    'orders.orderNumber': 'رقم الطلب',
    'orders.orderDate': 'تاريخ الطلب',
    'orders.viewDetails': 'عرض التفاصيل',
    'orders.trackOrder': 'تتبع الطلب',
    'orders.paymentStatus': 'حالة الدفع',
    'orders.trackingNumber': 'رقم التتبع',
    'orders.status.pending': 'قيد المعالجة',
    'orders.status.processing': 'جاري التجهيز',
    'orders.status.shipped': 'تم الشحن',
    'orders.status.delivered': 'تم التسليم',
    'orders.status.cancelled': 'ملغى',
    'orders.payment.paid': 'مدفوع',
    'orders.payment.pending': 'قيد الدفع',
    'orders.payment.failed': 'فشل الدفع',

    // Solar Calculator
    'calculator.title': 'حاسبة الطاقة الشمسية',
    'calculator.subtitle': 'اكتشف كم ستوفر عند تركيب نظام طاقة شمسية لمنزلك أو عملك',
    'calculator.consumption': 'استهلاك الكهرباء الشهري (كيلوواط/ساعة)',
    'calculator.usageType': 'نوع الاستخدام',
    'calculator.residential': 'منزلي',
    'calculator.commercial': 'تجاري',
    'calculator.industrial': 'صناعي',
    'calculator.agricultural': 'زراعي',
    'calculator.city': 'المدينة',
    'calculator.sunHours': 'متوسط ساعات الشمس اليومية',
    'calculator.systemType': 'نوع النظام',
    'calculator.onGrid': 'متصل بالشبكة',
    'calculator.offGrid': 'مستقل',
    'calculator.hybrid': 'هجين',
    'calculator.solarPump': 'مضخة شمسية',
    'calculator.calculate': 'احسب الآن',
    'calculator.calculating': 'جاري الحساب...',
    'calculator.results': 'نتائج الحساب',
    'calculator.panels': 'لوح شمسي',
    'calculator.capacity': 'كيلوواط',
    'calculator.inverter': 'كيلوواط إنفرتر',
    'calculator.battery': 'كيلوواط/ساعة بطاريات',
    'calculator.cost': 'التكلفة التقديرية',
    'calculator.annualSavings': 'التوفير السنوي',
    'calculator.payback': 'فترة الاسترداد',
    'calculator.lifetimeSavings': 'التوفير خلال 25 سنة',
    'calculator.co2Saved': 'انبعاثات CO2 المُوفَّرة سنوياً',
    'calculator.exportPDF': 'تصدير PDF',
    'calculator.sendEmail': 'إرسال بالبريد',
    'calculator.requestQuote': 'اطلب عرض سعر مخصص',
    'calculator.enterData': 'أدخل بياناتك',
    'calculator.financialAnalysis': 'التحليل المالي التفصيلي',
    'calculator.cumulativeSavings': 'التوفير التراكمي على مدار 25 سنة',
    'calculator.costDistribution': 'توزيع تكلفة النظام',
    'calculator.billComparison': 'مقارنة الفاتورة الشهرية',
    'calculator.monthlySavings': 'توفير شهري',
    'calculator.tips': 'نصائح لتحقيق أقصى استفادة',
    'calculator.features': 'مميزات الحاسبة',
    'calculator.comparison': 'مقارنة أنواع الأنظمة الشمسية',
    'calculator.faq': 'الأسئلة الشائعة',
    'calculator.systemSummary': 'ملخص النظام',
    'calculator.costBreakdown': 'تفصيل التكلفة',
    'calculator.savings': 'التوفير',
    'calculator.environmentalImpact': 'الأثر البيئي',
    'calculator.clientData': 'بيانات العميل',
    'calculator.siteData': 'بيانات الموقع',
    'calculator.consumptionData': 'بيانات الاستهلاك',
    'calculator.appliances': 'الأجهزة المنزلية',
    'calculator.saveQuote': 'حفظ العرض',
    'calculator.quotes': 'العروض المحفوظة',
    'calculator.reminders': 'التذكيرات',
    'calculator.pricingSettings': 'إعدادات الأسعار',

    // Contact
    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'نحن هنا لمساعدتك. تواصل معنا بأي طريقة تناسبك',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.phone': 'رقم الهاتف',
    'contact.form.subject': 'الموضوع',
    'contact.form.service': 'الخدمة المطلوبة',
    'contact.form.message': 'الرسالة',
    'contact.form.send': 'إرسال الرسالة',
    'contact.form.sending': 'جاري الإرسال...',
    'contact.form.success': 'تم إرسال رسالتك بنجاح',
    'contact.form.successDesc': 'سنتواصل معك في أقرب وقت ممكن',
    'contact.info.email': 'البريد الإلكتروني',
    'contact.info.phone': 'الهاتف',
    'contact.info.whatsapp': 'واتساب',
    'contact.info.address': 'العنوان',
    'contact.info.hours': 'ساعات العمل',
    'contact.cta.whatsapp': 'تواصل عبر واتساب',
    'contact.cta.call': 'اتصل بنا الآن',

    // About
    'about.title': 'من نحن',
    'about.subtitle': 'أعمال مازن الزبير للطاقة الشمسية - رائدة الحلول الهندسية في السودان',
    'about.story': 'قصتنا',
    'about.vision': 'رؤيتنا',
    'about.mission': 'مهمتنا',
    'about.values': 'قيمنا',
    'about.team': 'فريقنا',
    'about.history': 'تاريخنا',
    'about.cta.title': 'هل لديك مشروع في ذهنك؟',
    'about.cta.subtitle': 'نحن هنا لمساعدتك في تحويل أفكارك إلى واقع',
    'about.cta.button': 'تواصل معنا',

    // Projects
    'projects.title': 'مشاريعنا',
    'projects.subtitle': 'معرض أعمالنا ومشاريعنا المنجزة',
    'projects.all': 'جميع المشاريع',
    'projects.solar': 'الطاقة الشمسية',
    'projects.surveillance': 'أنظمة المراقبة',
    'projects.industrial': 'الماكينات الصناعية',
    'projects.viewProject': 'عرض المشروع',
    'projects.stats.projects': 'مشروع منجز',
    'projects.stats.capacity': 'ميجاواط مُركّبة',
    'projects.stats.clients': 'عميل راضٍ',
    'projects.cta.title': 'هل لديك مشروع جديد؟',
    'projects.cta.subtitle': 'تواصل معنا لمناقشة احتياجاتك والحصول على عرض أسعار',
    'projects.cta.button': 'ابدأ مشروعك',

    // Blog
    'blog.title': 'المدونة',
    'blog.subtitle': 'آخر الأخبار والمقالات المفيدة',
    'blog.readMore': 'اقرأ المزيد',
    'blog.readArticle': 'اقرأ المقال',
    'blog.allArticles': 'جميع المقالات',
    'blog.categories': 'التصنيفات',
    'blog.tags': 'الوسوم',
    'blog.share': 'مشاركة',
    'blog.relatedPosts': 'مقالات ذات صلة',
    'blog.noArticles': 'لا توجد مقالات حالياً',
    'blog.searchArticles': 'ابحث في المقالات...',
    'blog.browseAll': 'تصفح جميع المقالات',

    // Footer
    'footer.about': 'أعمال مازن الزبير للطاقة الشمسية - رائدة في حلول الطاقة الشمسية وأنظمة المراقبة في السودان',
    'footer.description': 'نقدم حلولاً هندسية متكاملة في مجالات الطاقة الشمسية، أنظمة المراقبة، والماكينات الصناعية بأعلى معايير الجودة والاحترافية.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.services': 'الخدمات',
    'footer.contact': 'تواصل معنا',
    'footer.rights': 'جميع الحقوق محفوظة',
    'footer.newsletter': 'النشرة البريدية',
    'footer.newsletter.desc': 'اشترك ليصلك آخر العروض والمشاريع والحلول الهندسية المميزة.',
    'footer.newsletter.placeholder': 'ادخل بريدك الإلكتروني',
    'footer.newsletter.subscribe': 'اشترك الآن',
    'footer.newsletter.subscribing': 'جارٍ الاشتراك...',
    'footer.newsletter.success': 'تم الاشتراك بنجاح',
    'footer.newsletter.successDesc': 'شكراً لانضمامك إلى نشرتنا البريدية.',
    'footer.privacyPolicy': 'سياسة الخصوصية',
    'footer.terms': 'الشروط والأحكام',
    'footer.adminPanel': 'لوحة التحكم',
    'footer.solarCalculator': 'حاسبة الطاقة الشمسية',
    'footer.maintenanceSupport': 'الصيانة والدعم الفني',

    // Auth
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.register': 'إنشاء حساب',
    'auth.myAccount': 'حسابي',
    'auth.welcome': 'مرحباً',

    // FAQ
    'faq.title': 'الأسئلة الشائعة',
    'faq.subtitle': 'إجابات على أكثر الأسئلة شيوعاً حول خدماتنا ومنتجاتنا',
    'faq.frequentQuestions': 'الأسئلة المتكررة',

    // Errors
    'error.notFound': 'الصفحة غير موجودة',
    'error.notFoundDesc': 'عذراً، لم نتمكن من العثور على الصفحة المطلوبة',
    'error.serverError': 'حدث خطأ في الخادم',
    'error.networkError': 'خطأ في الاتصال',
    'error.goHome': 'العودة للرئيسية',

    // Features
    'features.team': 'فريق هندسي متخصص ومؤهل',
    'features.warranty': 'ضمان شامل على جميع المنتجات',
    'features.support': 'دعم فني على مدار الساعة',
    'features.prices': 'أسعار تنافسية ومناسبة',
    'features.afterSales': 'خدمة ما بعد البيع ممتازة',
    'features.customSolutions': 'حلول مخصصة لاحتياجاتك',

    // Misc
    'misc.years': 'سنة',
    'misc.kg': 'كجم',
    'misc.trees': 'شجرة',
    'misc.equivalent': 'ما يعادل',
    'misc.treesPlanted': 'شجرة مزروعة',
    'misc.discoverMore': 'اكتشف المزيد',

    // PDF Export
    'pdf.title': 'عرض سعر نظام طاقة شمسية',
    'pdf.quoteNumber': 'رقم العرض',
    'pdf.date': 'التاريخ',
    'pdf.validUntil': 'صالح حتى',
    'pdf.customerData': 'بيانات العميل',
    'pdf.systemDetails': 'تفاصيل النظام',
    'pdf.financialSummary': 'الملخص المالي',
    'pdf.environmentalImpact': 'الأثر البيئي',
    'pdf.download': 'تحميل PDF',
    'pdf.print': 'طباعة',
    'pdf.sendEmail': 'إرسال بالبريد',
    'pdf.shareWhatsApp': 'مشاركة واتساب',
    'pdf.sending': 'جاري الإرسال...',
    'pdf.sent': 'تم الإرسال بنجاح',
    'pdf.enterEmail': 'أدخل البريد الإلكتروني',
    'pdf.enterName': 'اسم العميل',
    'pdf.enterPhone': 'رقم الهاتف',
    'pdf.exportResults': 'تصدير النتائج',
    'pdf.attachedPDF': 'تم إرفاق ملف PDF',

    // About Page
    'about.buildFuture': 'نبني المستقبل بخبرة وابتكار',
    'about.companyDesc1': 'أعمال مازن الزبير للطاقة الشمسية هي شركة سودانية رائدة تأسست عام 2008، متخصصة في تقديم حلول هندسية متكاملة في مجالات الطاقة الشمسية، أنظمة المراقبة والأمن، والماكينات الصناعية.',
    'about.companyDesc2': 'نفخر بأكثر من 15 عامًا من الخبرة و500 مشروع ناجح، ونسعى دائمًا لتقديم أفضل الحلول التي تلبي احتياجات عملائنا وتفوق توقعاتهم.',
    'about.qualifiedTeam': 'فريق هندسي متخصص ومؤهل',
    'about.globalPartners': 'شراكات مع أكبر الشركات العالمية',
    'about.comprehensiveWarranty': 'ضمان شامل على جميع المنتجات',
    'about.support247': 'دعم فني على مدار الساعة',
    'about.visionDesc': 'أن نكون الشركة الرائدة والمفضلة في تقديم الحلول الهندسية المتكاملة في السودان والمنطقة، والمساهمة في بناء مستقبل مستدام من خلال التقنيات الحديثة والابتكار المستمر.',
    'about.missionDesc': 'تقديم حلول هندسية عالية الجودة تلبي احتياجات عملائنا وتفوق توقعاتهم، مع الالتزام بأعلى معايير الاحترافية والأمانة، وبناء علاقات طويلة الأمد مع شركائنا وعملائنا.',
    'about.valueQuality': 'الجودة',
    'about.valueQualityDesc': 'نلتزم بأعلى معايير الجودة في جميع منتجاتنا وخدماتنا',
    'about.valueIntegrity': 'الأمانة',
    'about.valueIntegrityDesc': 'نتعامل بشفافية ومصداقية مع جميع عملائنا وشركائنا',
    'about.valueInnovation': 'الابتكار',
    'about.valueInnovationDesc': 'نسعى دائماً لتقديم حلول مبتكرة تواكب التطور التقني',
    'about.valueTeamwork': 'العمل الجماعي',
    'about.valueTeamworkDesc': 'نؤمن بقوة الفريق والتعاون لتحقيق أفضل النتائج',
    'about.timeline': 'مسيرتنا',
    'about.timelineDesc': 'رحلة نجاح مستمرة منذ التأسيس',
    'about.joinTeam': 'هل ترغب في العمل معنا؟',
    'about.joinTeamDesc': 'نحن دائماً نبحث عن المواهب المتميزة للانضمام لفريقنا',
    'about.knowUs': 'تعرف علينا',
    'about.principlesGuide': 'المبادئ التي توجه عملنا وتحدد هويتنا',
    'about.eliteEngineers': 'نخبة من المهندسين والخبراء المتخصصين',

    // Contact Page
    'contact.infoTitle': 'معلومات التواصل',
    'contact.infoSubtitle': 'يمكنك التواصل معنا من خلال أي من الوسائل التالية',
    'contact.sendMessage': 'أرسل رسالة',
    'contact.formDesc': 'املأ النموذج أدناه وسنتواصل معك في أقرب وقت',
    'contact.successTitle': 'تم الإرسال بنجاح!',
    'contact.successMessage': 'شكراً لتواصلك معنا. سنرد عليك في أقرب وقت ممكن.',
    'contact.sendingMessage': 'جاري الإرسال...',
    'contact.submitMessage': 'إرسال الرسالة',
    'contact.workingHours': 'السبت - الخميس: 8 ص - 5 م',
    'contact.haveQuestions': 'هل لديك أسئلة؟',
    'contact.dontHesitate': 'لا تتردد في الاتصال بنا مباشرة أو التواصل عبر واتساب',
    'contact.hereToHelp': 'نحن هنا لمساعدتك',
    'contact.happyToConnect': 'نسعد بتواصلك معنا والإجابة على جميع استفساراتك',
    'contact.chooseService': 'اختر الخدمة',
    'contact.requiredFields': 'يرجى تعبئة الحقول المطلوبة بشكل صحيح',
    'contact.messageSent': 'تم إرسال رسالتك بنجاح! سنتواصل معك قريباً',
    'contact.messageError': 'حدث خطأ أثناء إرسال الرسالة، يرجى المحاولة مرة أخرى',
    'contact.serviceSolar': 'حلول الطاقة الشمسية',
    'contact.serviceSurveillance': 'أنظمة المراقبة والأمن',
    'contact.serviceIndustrial': 'الماكينات الصناعية',
    'contact.serviceProduction': 'خطوط الإنتاج',
    'contact.serviceMaintenance': 'الصيانة والدعم الفني',
    'contact.serviceOther': 'أخرى',

    // Reviews
    'reviews.title': 'التقييمات',
    'reviews.writeReview': 'اكتب تقييماً',
    'reviews.addReview': 'إضافة تقييم',
    'reviews.rating': 'التقييم',
    'reviews.name': 'الاسم',
    'reviews.email': 'البريد الإلكتروني (اختياري)',
    'reviews.comment': 'التعليق',
    'reviews.images': 'الصور (اختياري - حتى 5 صور)',
    'reviews.submit': 'إرسال التقييم',
    'reviews.submitting': 'جاري الإرسال...',
    'reviews.success': 'تم إرسال التقييم!',
    'reviews.successDesc': 'سيتم نشر تقييمك بعد مراجعته من قبل الإدارة',
    'reviews.noReviews': 'لا توجد تقييمات بعد',
    'reviews.beFirst': 'كن أول من يقيم هذا المنتج',
    'reviews.verified': 'مشتري معتمد',
    'reviews.stars': 'نجوم',
    'reviews.totalReviews': 'تقييم',
    'reviews.loading': 'جاري التحميل...',
    'reviews.error': 'خطأ',
    'reviews.errorDesc': 'يرجى ملء جميع الحقول المطلوبة',
    'reviews.maxImages': 'يمكنك رفع 5 صور كحد أقصى',
    'reviews.shareFeedback': 'شاركنا رأيك حول المنتج...',

    // Comparison
    'compare.title': 'مقارنة المنتجات',
    'compare.add': 'أضف للمقارنة',
    'compare.remove': 'إزالة من المقارنة',
    'compare.clear': 'مسح الكل',
    'compare.compare': 'قارن',
    'compare.noProducts': 'لا توجد منتجات للمقارنة',
    'compare.addProducts': 'أضف منتجات للمقارنة',
    'compare.maxProducts': 'يمكنك مقارنة 4 منتجات كحد أقصى',
    'compare.specifications': 'المواصفات',
    'compare.price': 'السعر',
    'compare.stock': 'المخزون',
    'compare.category': 'الفئة',
    'compare.addToCart': 'أضف للسلة',
    'compare.viewDetails': 'عرض التفاصيل',
    'compare.productsSelected': 'منتجات مختارة',

    // Wishlist
    'wishlist.title': 'قائمة أمنياتي',
    'wishlist.add': 'أضف للمفضلة',
    'wishlist.remove': 'إزالة من المفضلة',
    'wishlist.empty': 'قائمة المفضلة فارغة',
    'wishlist.emptyDesc': 'أضف المنتجات التي تعجبك إلى قائمة المفضلة',
    'wishlist.browsProducts': 'تصفح المنتجات',
    'wishlist.added': 'تمت الإضافة للمفضلة',
    'wishlist.removed': 'تمت الإزالة من المفضلة',
    'wishlist.items': 'منتجات',
    'wishlist.moveToCart': 'نقل للسلة',
    'wishlist.clearAll': 'مسح الكل',

    // Testimonials
    'testimonials.title': 'ماذا يقول عملاؤنا',
    'testimonials.subtitle': 'استمع لآراء عملائنا الراضين',

    // Recently Viewed
    'recentlyViewed.title': 'شاهدت مؤخراً',
    'recentlyViewed.empty': 'لا توجد منتجات شاهدتها مؤخراً',

    // Social Proof
    'socialProof.justBought': 'اشترى للتو',
    'socialProof.viewing': 'شخص يشاهد هذا المنتج الآن',
    'socialProof.soldWeek': 'تم بيعها هذا الأسبوع',

    // Services Page
    'services.hero.badge': 'خدماتنا المتميزة',
    'services.hero.title': 'حلول هندسية متكاملة',
    'services.hero.subtitle': 'نقدم مجموعة شاملة من الخدمات الهندسية في مجالات الطاقة الشمسية، أنظمة المراقبة، والماكينات الصناعية بأعلى معايير الجودة',
    'services.getQuote': 'احصل على عرض سعر',
    'services.additionalProducts': 'منتجات إضافية',
    'services.additionalProductsDesc': 'نوفر مجموعة واسعة من المنتجات والمعدات عالية الجودة',
    'services.inverters': 'الانفرترات',
    'services.invertersDesc': 'انفرترات عالية الكفاءة',
    'services.batteries': 'البطاريات',
    'services.batteriesDesc': 'بطاريات ليثيوم متطورة',
    'services.recorders': 'أجهزة التسجيل',
    'services.recordersDesc': 'NVR و DVR احترافية',
    'services.spareParts': 'قطع الغيار',
    'services.sparePartsDesc': 'قطع غيار أصلية',
    'services.needConsultation': 'هل تحتاج استشارة؟',
    'services.consultationDesc': 'فريقنا الهندسي جاهز لمساعدتك في اختيار الحل الأمثل لاحتياجاتك',
    'services.callNow': 'اتصل الآن',

    // Projects Page
    'projects.hero.badge': 'أعمالنا السابقة',
    'projects.hero.title': 'مشاريعنا المنجزة',
    'projects.hero.subtitle': 'نفخر بتقديم أكثر من 500 مشروع ناجح في مختلف المجالات الهندسية',
    'projects.filter.all': 'الكل',
    'projects.viewDetails': 'عرض التفاصيل',
    'projects.location': 'الموقع',
    'projects.year': 'السنة',
    'projects.stats.completedProjects': 'مشروع منجز',
    'projects.stats.happyClients': 'عميل راضٍ',
    'projects.stats.yearsExperience': 'سنة خبرة',
    'projects.stats.engineers': 'مهندس متخصص',
    'projects.haveProject': 'هل لديك مشروع في ذهنك؟',
    'projects.contactToday': 'تواصل معنا اليوم ودعنا نحول فكرتك إلى واقع',
    'projects.startProject': 'ابدأ مشروعك الآن',

    // Blog Page
    'blog.hero.title': 'المدونة',
    'blog.hero.subtitle': 'آخر الأخبار والمقالات حول الطاقة الشمسية وأنظمة المراقبة والماكينات الصناعية',
    'blog.filter.category': 'التصنيف:',
    'blog.filter.tags': 'الوسوم:',
    'blog.noArticlesYet': 'لا توجد مقالات',
    'blog.articlesComing': 'سننشر مقالات قريباً، ترقبوا المزيد!',

    // Breadcrumbs
    'breadcrumb.home': 'الرئيسية',
    'breadcrumb.products': 'المنتجات',
    'breadcrumb.services': 'الخدمات',
    'breadcrumb.projects': 'المشاريع',
    'breadcrumb.blog': 'المدونة',
    'breadcrumb.about': 'من نحن',
    'breadcrumb.contact': 'اتصل بنا',
    'breadcrumb.cart': 'السلة',
    'breadcrumb.checkout': 'إتمام الطلب',
    'breadcrumb.orders': 'طلباتي',
    'breadcrumb.wishlist': 'المفضلة',
    'breadcrumb.compare': 'المقارنة',
    'breadcrumb.calculator': 'حاسبة الطاقة',
    'breadcrumb.dashboard': 'لوحة المستخدم',

    // Quick View Features
    'quickView.fastDelivery': 'توصيل سريع',
    'quickView.qualityGuarantee': 'ضمان الجودة',
    'quickView.originalProduct': 'منتج أصلي',
    'quickView.safePackaging': 'تغليف آمن',
    'quickView.save': 'توفير',
    'quickView.pieces': 'قطعة',
    'quickView.available': 'متوفر في المخزون',
    'quickView.notAvailable': 'غير متوفر',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.services': 'Services',
    'nav.projects': 'Projects',
    'nav.blog': 'Blog',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.calculator': 'Solar Calculator',
    'nav.cart': 'Cart',
    'nav.myOrders': 'My Orders',
    'nav.dashboard': 'Dashboard',
    'nav.getQuote': 'Get Quote',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.view': 'View',
    'common.download': 'Download',
    'common.print': 'Print',
    'common.share': 'Share',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.name': 'Name',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.language': 'Language',
    'common.arabic': 'العربية',
    'common.english': 'English',
    'common.moreInfo': 'More Info',
    'common.readMore': 'Read More',
    'common.viewAll': 'View All',
    'common.contactUs': 'Contact Us',
    'common.learnMore': 'Learn More',
    'common.getStarted': 'Get Started',
    'common.freeConsultation': 'Free Consultation',
    'common.currency': 'SDG',

    // Homepage
    'home.hero.title': 'Complete Energy Solutions for Sudan',
    'home.hero.subtitle': 'We provide the best solar energy, surveillance, and alarm systems with the highest quality and best prices',
    'home.hero.cta': 'Browse Products',
    'home.hero.calculator': 'Calculate Your Needs',
    'home.hero.freeConsultation': 'Get Free Consultation',
    'home.hero.discoverServices': 'Discover Our Services',
    'home.hero.trustedPartner': 'Your Trusted Partner in Engineering Solutions',
    'home.hero.integratedSolutions': 'Engineering Solutions',
    'home.hero.innovative': 'Integrated & Innovative',
    'home.hero.description': 'We provide the best solutions in solar energy, surveillance systems, and industrial machinery with the highest global quality standards',
    'home.hero.mainTitle': 'Building a Sustainable Future with Clean Energy',
    'home.hero.mainSubtitle': 'Leaders in Solar Energy, Security Systems & Industrial Machinery in Sudan',
    'home.hero.since': 'Since 2009',
    'home.hero.companyName': 'Mazen Alzubair Solar Works',
    'home.featured': 'Featured Products',
    'home.featured.title': 'Discover Our Best Products',
    'home.featured.subtitle': 'A curated selection of the best products in solar energy, surveillance systems, and industrial machinery',
    'home.featured.viewAll': 'View All Products',
    'home.services': 'Our Services',
    'home.services.title': 'Our Distinguished Services',
    'home.services.subtitle': 'We offer a comprehensive range of specialized engineering services',
    'home.projects': 'Our Projects',
    'home.projects.title': 'Our Latest Projects',
    'home.projects.subtitle': 'We are proud of our successful projects across Sudan',
    'home.blog': 'Latest Articles',
    'home.blog.title': 'Our Blog',
    'home.blog.subtitle': 'Latest news and useful articles in energy and technology',
    'home.blog.readArticle': 'Read Article',
    'home.contact': 'Contact Us',
    'home.newsletter': 'Newsletter',
    'home.newsletter.desc': 'Subscribe to our newsletter for the latest offers and news',
    'home.stats.projects': 'Projects Completed',
    'home.stats.experience': 'Years Experience',
    'home.stats.clients': 'Happy Clients',
    'home.stats.support': 'Technical Support',
    'home.whyUs': 'Why Us?',
    'home.whyUs.title': 'Why Choose Mazen Alzubair Solar Works?',
    'home.whyUs.subtitle': 'We excel in quality and professionalism in all our services',
    'home.cta.title': 'Ready to Start Your Project?',
    'home.cta.subtitle': 'Contact us today for a free consultation and a customized quote for your needs',
    'home.cta.button': 'Contact Us Now',
    'home.cta.whatsapp': 'Contact via WhatsApp',

    // Services
    'services.solar.title': 'Solar Energy Solutions',
    'services.solar.desc': 'Integrated solar energy systems for homes, commercial, and industrial facilities with quality and high efficiency guarantee',
    'services.surveillance.title': 'Surveillance & Security Systems',
    'services.surveillance.desc': 'High-definition surveillance cameras from Hikvision with advanced security solutions to protect your property',
    'services.industrial.title': 'Industrial Machinery',
    'services.industrial.desc': 'Packaging machines and integrated production lines with technical support and maintenance',
    'services.maintenance.title': 'Maintenance & Support',
    'services.maintenance.desc': 'Periodic maintenance services and continuous technical support for all systems',

    // Products
    'products.title': 'Our Products',
    'products.subtitle': 'Discover our wide range of high-quality products',
    'products.search': 'Search for a product...',
    'products.category': 'Category',
    'products.price': 'Price',
    'products.sort': 'Sort by',
    'products.sortNewest': 'Newest',
    'products.sortPriceAsc': 'Price: Low to High',
    'products.sortPriceDesc': 'Price: High to Low',
    'products.sortNameAsc': 'Name: A-Z',
    'products.new': 'New',
    'products.discount': 'Discount',
    'products.outOfStock': 'Out of Stock',
    'products.inStock': 'In Stock',
    'products.lowStock': 'Limited Stock',
    'products.addToCart': 'Add to Cart',
    'products.addedToCart': 'Added to Cart',
    'products.quickView': 'Quick View',
    'products.details': 'Product Details',
    'products.specifications': 'Specifications',
    'products.reviews': 'Reviews',
    'products.related': 'Related Products',
    'products.features': 'Features',
    'products.description': 'Description',
    'products.noProducts': 'No products found',
    'products.itemsLeft': 'Only {count} items left!',
    'products.showFilters': 'Show Filters',
    'products.hideFilters': 'Hide Filters',
    'products.priceRange': 'Price Range',
    'products.availability': 'Availability',
    'products.onSale': 'On Sale',

    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.emptyDesc': "You haven't added any products yet. Start shopping now!",
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.shippingFree': 'Free',
    'cart.shippingCalc': 'Calculated at checkout',
    'cart.discount': 'Discount',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.coupon': 'Coupon Code',
    'cart.applyCoupon': 'Apply',
    'cart.remove': 'Remove',
    'cart.updateQuantity': 'Update Quantity',
    'cart.orderSummary': 'Order Summary',

    // Checkout
    'checkout.title': 'Checkout',
    'checkout.customerInfo': 'Customer Information',
    'checkout.shippingAddress': 'Shipping Address',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.cashOnDelivery': 'Cash on Delivery',
    'checkout.bankTransfer': 'Bank Transfer',
    'checkout.placeOrder': 'Place Order',
    'checkout.processing': 'Processing order...',
    'checkout.fullName': 'Full Name',
    'checkout.email': 'Email',
    'checkout.phone': 'Phone Number',
    'checkout.city': 'City',
    'checkout.address': 'Detailed Address',
    'checkout.notes': 'Additional Notes',

    // Orders
    'orders.title': 'My Orders',
    'orders.empty': 'No orders yet',
    'orders.emptyDesc': 'Start shopping now to create your first order.',
    'orders.browseProducts': 'Browse Products',
    'orders.orderNumber': 'Order Number',
    'orders.orderDate': 'Order Date',
    'orders.viewDetails': 'View Details',
    'orders.trackOrder': 'Track Order',
    'orders.paymentStatus': 'Payment Status',
    'orders.trackingNumber': 'Tracking Number',
    'orders.status.pending': 'Pending',
    'orders.status.processing': 'Processing',
    'orders.status.shipped': 'Shipped',
    'orders.status.delivered': 'Delivered',
    'orders.status.cancelled': 'Cancelled',
    'orders.payment.paid': 'Paid',
    'orders.payment.pending': 'Pending',
    'orders.payment.failed': 'Failed',

    // Solar Calculator
    'calculator.title': 'Solar Energy Calculator',
    'calculator.subtitle': 'Discover how much you can save by installing a solar energy system for your home or business',
    'calculator.consumption': 'Monthly Electricity Consumption (kWh)',
    'calculator.usageType': 'Usage Type',
    'calculator.residential': 'Residential',
    'calculator.commercial': 'Commercial',
    'calculator.industrial': 'Industrial',
    'calculator.agricultural': 'Agricultural',
    'calculator.city': 'City',
    'calculator.sunHours': 'Average Daily Sun Hours',
    'calculator.systemType': 'System Type',
    'calculator.onGrid': 'On-Grid',
    'calculator.offGrid': 'Off-Grid',
    'calculator.hybrid': 'Hybrid',
    'calculator.solarPump': 'Solar Pump',
    'calculator.calculate': 'Calculate Now',
    'calculator.calculating': 'Calculating...',
    'calculator.results': 'Calculation Results',
    'calculator.panels': 'Solar Panels',
    'calculator.capacity': 'kW',
    'calculator.inverter': 'kW Inverter',
    'calculator.battery': 'kWh Batteries',
    'calculator.cost': 'Estimated Cost',
    'calculator.annualSavings': 'Annual Savings',
    'calculator.payback': 'Payback Period',
    'calculator.lifetimeSavings': 'Lifetime Savings (25 years)',
    'calculator.co2Saved': 'Annual CO2 Emissions Saved',
    'calculator.exportPDF': 'Export PDF',
    'calculator.sendEmail': 'Send by Email',
    'calculator.requestQuote': 'Request Custom Quote',
    'calculator.enterData': 'Enter Your Data',
    'calculator.financialAnalysis': 'Detailed Financial Analysis',
    'calculator.cumulativeSavings': 'Cumulative Savings Over 25 Years',
    'calculator.costDistribution': 'System Cost Distribution',
    'calculator.billComparison': 'Monthly Bill Comparison',
    'calculator.monthlySavings': 'Monthly Savings',
    'calculator.tips': 'Tips for Maximum Benefit',
    'calculator.features': 'Calculator Features',
    'calculator.comparison': 'Solar System Types Comparison',
    'calculator.faq': 'Frequently Asked Questions',
    'calculator.systemSummary': 'System Summary',
    'calculator.costBreakdown': 'Cost Breakdown',
    'calculator.savings': 'Savings',
    'calculator.environmentalImpact': 'Environmental Impact',
    'calculator.clientData': 'Client Data',
    'calculator.siteData': 'Site Data',
    'calculator.consumptionData': 'Consumption Data',
    'calculator.appliances': 'Appliances',
    'calculator.saveQuote': 'Save Quote',
    'calculator.quotes': 'Saved Quotes',
    'calculator.reminders': 'Reminders',
    'calculator.pricingSettings': 'Pricing Settings',

    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are here to help. Contact us in any way that suits you',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.phone': 'Phone Number',
    'contact.form.subject': 'Subject',
    'contact.form.service': 'Required Service',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Your message has been sent successfully',
    'contact.form.successDesc': 'We will contact you as soon as possible',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.whatsapp': 'WhatsApp',
    'contact.info.address': 'Address',
    'contact.info.hours': 'Working Hours',
    'contact.cta.whatsapp': 'Contact via WhatsApp',
    'contact.cta.call': 'Call Us Now',

    // About
    'about.title': 'About Us',
    'about.subtitle': 'Mazen Alzubair Solar Works - Leading Engineering Solutions in Sudan',
    'about.story': 'Our Story',
    'about.vision': 'Our Vision',
    'about.mission': 'Our Mission',
    'about.values': 'Our Values',
    'about.team': 'Our Team',
    'about.history': 'Our History',
    'about.cta.title': 'Have a project in mind?',
    'about.cta.subtitle': 'We are here to help turn your ideas into reality',
    'about.cta.button': 'Contact Us',

    // Projects
    'projects.title': 'Our Projects',
    'projects.subtitle': 'Portfolio of our completed projects',
    'projects.all': 'All Projects',
    'projects.solar': 'Solar Energy',
    'projects.surveillance': 'Surveillance Systems',
    'projects.industrial': 'Industrial Machinery',
    'projects.viewProject': 'View Project',
    'projects.stats.projects': 'Projects Completed',
    'projects.stats.capacity': 'MW Installed',
    'projects.stats.clients': 'Happy Clients',
    'projects.cta.title': 'Have a new project?',
    'projects.cta.subtitle': 'Contact us to discuss your needs and get a quote',
    'projects.cta.button': 'Start Your Project',

    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Latest news and useful articles',
    'blog.readMore': 'Read More',
    'blog.readArticle': 'Read Article',
    'blog.allArticles': 'All Articles',
    'blog.categories': 'Categories',
    'blog.tags': 'Tags',
    'blog.share': 'Share',
    'blog.relatedPosts': 'Related Posts',
    'blog.noArticles': 'No articles available',
    'blog.searchArticles': 'Search articles...',
    'blog.browseAll': 'Browse All Articles',

    // Footer
    'footer.about': 'Mazen Alzubair Solar Works - Leading in solar energy solutions and surveillance systems in Sudan',
    'footer.description': 'We provide integrated engineering solutions in solar energy, surveillance systems, and industrial machinery with the highest standards of quality and professionalism.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Services',
    'footer.contact': 'Contact Us',
    'footer.rights': 'All rights reserved',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.desc': 'Subscribe for the latest offers, projects, and distinguished engineering solutions.',
    'footer.newsletter.placeholder': 'Enter your email',
    'footer.newsletter.subscribe': 'Subscribe Now',
    'footer.newsletter.subscribing': 'Subscribing...',
    'footer.newsletter.success': 'Subscribed Successfully',
    'footer.newsletter.successDesc': 'Thank you for joining our newsletter.',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.adminPanel': 'Admin Panel',
    'footer.solarCalculator': 'Solar Calculator',
    'footer.maintenanceSupport': 'Maintenance & Support',

    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.register': 'Register',
    'auth.myAccount': 'My Account',
    'auth.welcome': 'Welcome',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Answers to the most common questions about our services and products',
    'faq.frequentQuestions': 'FAQ',

    // Errors
    'error.notFound': 'Page not found',
    'error.notFoundDesc': 'Sorry, we could not find the page you are looking for',
    'error.serverError': 'Server error occurred',
    'error.networkError': 'Network error',
    'error.goHome': 'Go to Home',

    // Features
    'features.team': 'Specialized and qualified engineering team',
    'features.warranty': 'Comprehensive warranty on all products',
    'features.support': '24/7 technical support',
    'features.prices': 'Competitive and affordable prices',
    'features.afterSales': 'Excellent after-sales service',
    'features.customSolutions': 'Customized solutions for your needs',

    // Misc
    'misc.years': 'years',
    'misc.kg': 'kg',
    'misc.trees': 'trees',
    'misc.equivalent': 'equivalent to',
    'misc.treesPlanted': 'trees planted',
    'misc.discoverMore': 'Discover More',

    // PDF Export
    'pdf.title': 'Solar Energy System Quote',
    'pdf.quoteNumber': 'Quote Number',
    'pdf.date': 'Date',
    'pdf.validUntil': 'Valid Until',
    'pdf.customerData': 'Customer Data',
    'pdf.systemDetails': 'System Details',
    'pdf.financialSummary': 'Financial Summary',
    'pdf.environmentalImpact': 'Environmental Impact',
    'pdf.download': 'Download PDF',
    'pdf.print': 'Print',
    'pdf.sendEmail': 'Send by Email',
    'pdf.shareWhatsApp': 'Share on WhatsApp',
    'pdf.sending': 'Sending...',
    'pdf.sent': 'Sent Successfully',
    'pdf.enterEmail': 'Enter Email',
    'pdf.enterName': 'Customer Name',
    'pdf.enterPhone': 'Phone Number',
    'pdf.exportResults': 'Export Results',
    'pdf.attachedPDF': 'PDF Attached',

    // About Page
    'about.buildFuture': 'Building the Future with Experience and Innovation',
    'about.companyDesc1': 'Mazen Alzubair Solar Works is a leading Sudanese company founded in 2008, specialized in providing integrated engineering solutions in solar energy, surveillance and security systems, and industrial machinery.',
    'about.companyDesc2': 'We are proud of over 15 years of experience and 500+ successful projects, and we always strive to provide the best solutions that meet our customers\' needs and exceed their expectations.',
    'about.qualifiedTeam': 'Specialized and qualified engineering team',
    'about.globalPartners': 'Partnerships with major global companies',
    'about.comprehensiveWarranty': 'Comprehensive warranty on all products',
    'about.support247': '24/7 technical support',
    'about.visionDesc': 'To be the leading and preferred company in providing integrated engineering solutions in Sudan and the region, and to contribute to building a sustainable future through modern technologies and continuous innovation.',
    'about.missionDesc': 'To provide high-quality engineering solutions that meet our customers\' needs and exceed their expectations, while adhering to the highest standards of professionalism and integrity, and building long-term relationships with our partners and customers.',
    'about.valueQuality': 'Quality',
    'about.valueQualityDesc': 'We are committed to the highest quality standards in all our products and services',
    'about.valueIntegrity': 'Integrity',
    'about.valueIntegrityDesc': 'We deal with transparency and credibility with all our customers and partners',
    'about.valueInnovation': 'Innovation',
    'about.valueInnovationDesc': 'We always strive to provide innovative solutions that keep pace with technological development',
    'about.valueTeamwork': 'Teamwork',
    'about.valueTeamworkDesc': 'We believe in the power of teamwork and collaboration to achieve the best results',
    'about.timeline': 'Our Journey',
    'about.timelineDesc': 'A continuous success journey since establishment',
    'about.joinTeam': 'Want to Work With Us?',
    'about.joinTeamDesc': 'We are always looking for distinguished talents to join our team',
    'about.knowUs': 'Know Us',
    'about.principlesGuide': 'The principles that guide our work and define our identity',
    'about.eliteEngineers': 'Elite engineers and specialized experts',

    // Contact Page
    'contact.infoTitle': 'Contact Information',
    'contact.infoSubtitle': 'You can reach us through any of the following methods',
    'contact.sendMessage': 'Send a Message',
    'contact.formDesc': 'Fill out the form below and we will contact you as soon as possible',
    'contact.successTitle': 'Sent Successfully!',
    'contact.successMessage': 'Thank you for contacting us. We will reply to you as soon as possible.',
    'contact.sendingMessage': 'Sending...',
    'contact.submitMessage': 'Send Message',
    'contact.workingHours': 'Sat - Thu: 8 AM - 5 PM',
    'contact.haveQuestions': 'Have Questions?',
    'contact.dontHesitate': 'Don\'t hesitate to call us directly or contact us via WhatsApp',
    'contact.hereToHelp': 'We\'re Here to Help',
    'contact.happyToConnect': 'We are happy to connect with you and answer all your inquiries',
    'contact.chooseService': 'Choose Service',
    'contact.requiredFields': 'Please fill in the required fields correctly',
    'contact.messageSent': 'Your message has been sent successfully! We will contact you soon',
    'contact.messageError': 'An error occurred while sending the message, please try again',
    'contact.serviceSolar': 'Solar Energy Solutions',
    'contact.serviceSurveillance': 'Surveillance & Security Systems',
    'contact.serviceIndustrial': 'Industrial Machinery',
    'contact.serviceProduction': 'Production Lines',
    'contact.serviceMaintenance': 'Maintenance & Technical Support',
    'contact.serviceOther': 'Other',

    // Reviews
    'reviews.title': 'Reviews',
    'reviews.writeReview': 'Write a Review',
    'reviews.addReview': 'Add Review',
    'reviews.rating': 'Rating',
    'reviews.name': 'Name',
    'reviews.email': 'Email (optional)',
    'reviews.comment': 'Comment',
    'reviews.images': 'Images (optional - up to 5)',
    'reviews.submit': 'Submit Review',
    'reviews.submitting': 'Submitting...',
    'reviews.success': 'Review Submitted!',
    'reviews.successDesc': 'Your review will be published after admin approval',
    'reviews.noReviews': 'No reviews yet',
    'reviews.beFirst': 'Be the first to review this product',
    'reviews.verified': 'Verified Buyer',
    'reviews.stars': 'stars',
    'reviews.totalReviews': 'reviews',
    'reviews.loading': 'Loading...',
    'reviews.error': 'Error',
    'reviews.errorDesc': 'Please fill in all required fields',
    'reviews.maxImages': 'You can upload up to 5 images',
    'reviews.shareFeedback': 'Share your feedback about this product...',

    // Comparison
    'compare.title': 'Compare Products',
    'compare.add': 'Add to Compare',
    'compare.remove': 'Remove from Compare',
    'compare.clear': 'Clear All',
    'compare.compare': 'Compare',
    'compare.noProducts': 'No products to compare',
    'compare.addProducts': 'Add products to compare',
    'compare.maxProducts': 'You can compare up to 4 products',
    'compare.specifications': 'Specifications',
    'compare.price': 'Price',
    'compare.stock': 'Stock',
    'compare.category': 'Category',
    'compare.addToCart': 'Add to Cart',
    'compare.viewDetails': 'View Details',
    'compare.productsSelected': 'products selected',

    // Wishlist
    'wishlist.title': 'My Wishlist',
    'wishlist.add': 'Add to Wishlist',
    'wishlist.remove': 'Remove from Wishlist',
    'wishlist.empty': 'Your wishlist is empty',
    'wishlist.emptyDesc': 'Add products you like to your wishlist',
    'wishlist.browsProducts': 'Browse Products',
    'wishlist.added': 'Added to Wishlist',
    'wishlist.removed': 'Removed from Wishlist',
    'wishlist.items': 'items',
    'wishlist.moveToCart': 'Move to Cart',
    'wishlist.clearAll': 'Clear All',

    // Testimonials
    'testimonials.title': 'What Our Customers Say',
    'testimonials.subtitle': 'Hear from our satisfied customers',

    // Recently Viewed
    'recentlyViewed.title': 'Recently Viewed',
    'recentlyViewed.empty': 'No recently viewed products',

    // Social Proof
    'socialProof.justBought': 'just purchased',
    'socialProof.viewing': 'people are viewing this now',
    'socialProof.soldWeek': 'sold this week',

    // Services Page
    'services.hero.badge': 'Our Distinguished Services',
    'services.hero.title': 'Integrated Engineering Solutions',
    'services.hero.subtitle': 'We offer a comprehensive range of engineering services in solar energy, surveillance systems, and industrial machinery with the highest quality standards',
    'services.getQuote': 'Get a Quote',
    'services.additionalProducts': 'Additional Products',
    'services.additionalProductsDesc': 'We provide a wide range of high-quality products and equipment',
    'services.inverters': 'Inverters',
    'services.invertersDesc': 'High-efficiency inverters',
    'services.batteries': 'Batteries',
    'services.batteriesDesc': 'Advanced lithium batteries',
    'services.recorders': 'Recording Devices',
    'services.recordersDesc': 'Professional NVR & DVR',
    'services.spareParts': 'Spare Parts',
    'services.sparePartsDesc': 'Original spare parts',
    'services.needConsultation': 'Need a Consultation?',
    'services.consultationDesc': 'Our engineering team is ready to help you choose the best solution for your needs',
    'services.callNow': 'Call Now',

    // Projects Page
    'projects.hero.badge': 'Our Previous Work',
    'projects.hero.title': 'Completed Projects',
    'projects.hero.subtitle': 'We are proud of completing more than 500 successful projects in various engineering fields',
    'projects.filter.all': 'All',
    'projects.viewDetails': 'View Details',
    'projects.location': 'Location',
    'projects.year': 'Year',
    'projects.stats.completedProjects': 'Completed Projects',
    'projects.stats.happyClients': 'Happy Clients',
    'projects.stats.yearsExperience': 'Years Experience',
    'projects.stats.engineers': 'Specialized Engineers',
    'projects.haveProject': 'Have a project in mind?',
    'projects.contactToday': 'Contact us today and let us turn your idea into reality',
    'projects.startProject': 'Start Your Project Now',

    // Blog Page
    'blog.hero.title': 'Blog',
    'blog.hero.subtitle': 'Latest news and articles about solar energy, surveillance systems, and industrial machinery',
    'blog.filter.category': 'Category:',
    'blog.filter.tags': 'Tags:',
    'blog.noArticlesYet': 'No articles yet',
    'blog.articlesComing': 'Articles will be published soon, stay tuned!',

    // Breadcrumbs
    'breadcrumb.home': 'Home',
    'breadcrumb.products': 'Products',
    'breadcrumb.services': 'Services',
    'breadcrumb.projects': 'Projects',
    'breadcrumb.blog': 'Blog',
    'breadcrumb.about': 'About Us',
    'breadcrumb.contact': 'Contact',
    'breadcrumb.cart': 'Cart',
    'breadcrumb.checkout': 'Checkout',
    'breadcrumb.orders': 'My Orders',
    'breadcrumb.wishlist': 'Wishlist',
    'breadcrumb.compare': 'Compare',
    'breadcrumb.calculator': 'Solar Calculator',
    'breadcrumb.dashboard': 'Dashboard',

    // Quick View Features
    'quickView.fastDelivery': 'Fast Delivery',
    'quickView.qualityGuarantee': 'Quality Guarantee',
    'quickView.originalProduct': 'Original Product',
    'quickView.safePackaging': 'Safe Packaging',
    'quickView.save': 'Save',
    'quickView.pieces': 'pieces',
    'quickView.available': 'available in stock',
    'quickView.notAvailable': 'Not Available',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ar';
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export { translations };
export type { Language };
